version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432 # Thay đổi từ 5433 thành 5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=fin_manager_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - '5432:5432' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fin_manager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
